spring:
  application:
    name: general-service
  datasource:
    url: jdbc:postgresql://localhost:5432/localchat_general-service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  liquibase.enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 0 # random port will be assigned
  tomcat:
    max-swallow-size: 600MB
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


token:
  signing:
    key: CL4loYvrbmPO6W8wf87q4S+7TttZKBCL6mYWQo4gVOA=

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springfox:
  documentation:
    swagger-ui:
      enabled: false
    swagger:
      v2:
        enabled: false
    open-api:
      enabled: false
    enabled: false

logging:
  level:
    org.springframework.orm.jpa.JpaTransactionManager: debug

minio:
  url: http://localhost:9000
  access-key: asdfas
  secret-key: asdasd
  bucket: asdasd
  expiration-days: 90